<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ycad</string>
	</array>
	<key>name</key>
	<string>ycad</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ycad</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.ycad</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.ycad</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Numeric value</string>
			<key>match</key>
			<string>[0-9]+(?:\.[0-9]+)?(mm|cm|m|inch)?</string>
			<key>name</key>
			<string>constant.numeric.ycad</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.multi-line.ycad</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Single-line string</string>
			<key>match</key>
			<string>"(?:.|\")+"</string>
			<key>name</key>
			<string>string.quoted.double.single-line.ycad</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.ycad</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ycad function definition</string>
			<key>match</key>
			<string>\bfunc\s+([A-Za-z][A-Za-z0-9_]*)\b</string>
			<key>name</key>
			<string>storage.type.function.ycad</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>ycad keyword</string>
			<key>match</key>
			<string>\bpart\b</string>
			<key>name</key>
			<string>storage.type.part.ycad</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>ycad keyword</string>
			<key>match</key>
			<string>\b(true|false|return|if|else|for|in|import)\b</string>
			<key>name</key>
			<string>keyword.source.ycad</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>built-in function</string>
			<key>match</key>
			<string>\b(move|rotate|scale)\b</string>
			<key>name</key>
			<string>support.function.runtime.ycad</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>csg block</string>
			<key>match</key>
			<string>\b(add|sub|mul)\b</string>
			<key>name</key>
			<string>support.function.csg.ycad</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variables</string>
			<key>match</key>
			<string>[A-Za-z][A-Za-z0-9_]*</string>
			<key>name</key>
			<string>variable.ycad</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\[\]\(\){}]</string>
			<key>name</key>
			<string>punctuation.ycad</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ycad</string>
	<key>uuid</key>
	<string>791d1ef1-8366-4ecb-88e5-228e8c3a17b2</string>
</dict>
</plist>
